//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CultOfJakito.UltraTelephone2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CultOfJakito.UltraTelephone2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mega
        ///Based
        ///Cringe
        ///Super
        ///Gay
        ///ULTRA
        ///Pro
        ///Hyper
        ///Peak
        ///Noob
        ///Final
        ///Ultimate
        ///Cowardly
        ///Elite
        ///Blue
        ///Red
        ///Stupid
        ///Stinky
        ///Smelly
        ///Lazy
        ///Awesome
        ///Magic
        ///Evil
        ///Kind
        ///The
        ///Skibidi
        ///Powerful
        ///Disgusting
        ///THE AMAZING
        ///Mid
        ///Masterful
        ///Goopy
        ///Funny
        ///Friendly
        ///Hostile
        ///LORD
        ///HOLY
        ///SAINT
        ///GOOBER
        ///PSYCHO
        ///BADASS
        ///GLISTENING
        ///BURNING.
        /// </summary>
        internal static string bossBar_prefixes {
            get {
                return ResourceManager.GetString("bossBar_prefixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE MAN
        ///(FINAL FORM)
        ///I
        ///II
        ///III
        ///IV
        ///V
        ///VI
        ///VII
        ///VIII
        ///IX
        ///X
        ///PHD
        ///FROM OHIO
        ///WITH RIZZ
        ///JR.
        ///SR.
        ///ESQUIRE
        ///LORD OF CINDER
        ///LORD OF HELL
        ///OCCUPANT OF HELL
        ///BOSS
        ///PRIME
        ///THE FIFTH
        ///HELLS GUARDIAN
        ///SWAG MASTER.
        /// </summary>
        internal static string bossBar_suffixes {
            get {
                return ResourceManager.GetString("bossBar_suffixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string cantReadWords {
            get {
                return ResourceManager.GetString("cantReadWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] hydra {
            get {
                object obj = ResourceManager.GetObject("hydra", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totally tubular
        ///Better than UltraTelephone!
        ///ULTRAWHO?
        ///Minos Prime
        ///I&apos;m going to ultrakill you
        ///Welcome Noobs!
        ///Have fun.
        ///,&apos;:]
        ///FREE P RANK DOWNLOAD NOW!
        ///In the end it has to be this way.
        ///Made with love &lt;3
        ///CULT OF JAKITO SENDS ITS REGARDS!
        ///What&apos;s weave?
        ///ULTRAMOD MANAGER!
        ///Ultramodded ULTRAKILL
        ///ULTRAULTRAKILL
        ///play primordial hunger on the angry level loader
        ///Rated M for Machine
        ///HOW TO GET FREE P-RANK ULTRAKILL
        ///Hello Machine.
        ///Hello Machines.
        ///Hello Machines..
        ///Who are you?
        ///Good luck.
        ///It is a sa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string splashes {
            get {
                return ResourceManager.GetString("splashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TelephoneMod {
            get {
                object obj = ResourceManager.GetObject("TelephoneMod", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] zed {
            get {
                object obj = ResourceManager.GetObject("zed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] zelzmiy {
            get {
                object obj = ResourceManager.GetObject("zelzmiy", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
