//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CultOfJakito.UltraTelephone2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CultOfJakito.UltraTelephone2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mega
        ///Based
        ///Cringe
        ///Super
        ///Gay
        ///Aromantic
        ///ULTRA
        ///Pro
        ///Hyper
        ///Peak
        ///Noob
        ///Final
        ///Ultimate
        ///Cowardly
        ///Elite
        ///Blue
        ///Red
        ///Stupid
        ///Stinky
        ///Smelly
        ///Lazy
        ///Awesome
        ///Magic
        ///Evil
        ///Kind
        ///The
        ///Skibidi
        ///Powerful
        ///Disgusting
        ///THE AMAZING
        ///Mid
        ///Masterful
        ///Goopy
        ///Funny
        ///Friendly
        ///Hostile
        ///LORD
        ///HOLY
        ///SAINT
        ///GOOBER
        ///PSYCHO
        ///BADASS
        ///GLISTENING
        ///BURNING
        ///Sir.
        ///Upside-Down
        ///Confused
        ///Listless
        ///Generous
        ///Blocky
        ///Round
        ///Enraged
        ///Angry
        ///Rude
        ///Rotund
        ///Caffeinated
        ///Combustable
        ///Menacing
        ///Fast
        ///Heroic
        ///Fair
        ///Epic
        ///Legendary
        ///Odd
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bossBar_prefixes {
            get {
                return ResourceManager.GetString("bossBar_prefixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE MAN
        ///(FINAL FORM)
        ///I
        ///II
        ///III
        ///IV
        ///V
        ///VI
        ///VII
        ///VIII
        ///IX
        ///X
        ///PHD
        ///M.D
        ///FROM OHIO
        ///WITH RIZZ
        ///JR.
        ///SR.
        ///ESQUIRE
        ///LORD OF CINDER
        ///LORD OF HELL
        ///OCCUPANT OF HELL
        ///BOSS
        ///PRIME
        ///THE FIFTH
        ///HELLS GUARDIAN
        ///SWAG MASTER
        ///The Everlasting
        ///The Desolate
        ///The Destroyer
        ///The Hungry
        ///:3
        ///The Squeamish
        ///The Tired
        ///The Broken
        ///The Cold
        ///The Abstracted
        ///B.A
        ///B.Sc
        ///M.A
        ///M.L.A. 
        ///M.F.A. 
        ///M.S.W. 
        ///M.L.
        ///B.Tech
        ///B.Ed
        ///Monarch
        ///DD
        ///OFM
        ///CSV
        ///The Incomplete
        ///The Rushed
        ///The Anointed
        ///The Revived
        ///Estranged.
        /// </summary>
        internal static string bossBar_suffixes {
            get {
                return ResourceManager.GetString("bossBar_suffixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when
        ///you
        ///and
        ///the
        ///then
        ///when
        ///we
        ///was
        ///where
        ///and
        ///then
        ///he
        ///she
        ///they
        ///and
        ///it
        ///was
        ///awesome
        ///then
        ///you
        ///just
        ///about
        ///to
        ///too
        ///there
        ///their
        ///then
        ///they&apos;re
        ///not
        ///very
        ///huge
        ///big
        ///small
        ///sand-covered
        ///silly
        ///:3.
        /// </summary>
        internal static string cantReadWords {
            get {
                return ResourceManager.GetString("cantReadWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] catalog_wbp_hash {
            get {
                object obj = ResourceManager.GetObject("catalog_wbp_hash", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] catalog_wbp_json {
            get {
                object obj = ResourceManager.GetObject("catalog_wbp_json", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydraxous
        ///Waffle
        ///Zelzmiy
        ///Teamdoodz
        ///ZedDev
        ///Glitchy
        ///Agent Of Nyarlathotep
        ///JAKITO
        ///Hakita
        ///PITR
        ///Heckteck
        ///Action Dawg
        ///.
        /// </summary>
        internal static string enemyNames {
            get {
                return ResourceManager.GetString("enemyNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your legs get cut off, would it hurt?
        ///101110010000101101011101101010110
        ///Weeeeeeeeeeeeeeeee
        ///How the fuck did a 1000-THR get in hell
        ///I thought a cerberus was a type of dog...
        ///What exactly generates the power from blood?
        ///Do guttermen dream?
        ///If Sisyphus could just break out of the prison, why did he wait?
        ///I just [EXCEPTION][EXCEPTION][EXCEPTION] Mindflayer [EXCEPTION]
        ///What if Guttertanks were always meant to topple?
        ///What if he made it up?
        ///What the heck them blue orbs
        ///What does P even stand for? P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ponder {
            get {
                return ResourceManager.GetString("ponder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] shader_unitybuiltinshaders {
            get {
                object obj = ResourceManager.GetObject("shader_unitybuiltinshaders", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you know you can shoot enemies to hurt them
        ///Hit the boss until its health bar is empty to win
        ///You can also dodge attacks by moving out of the way
        ///You can also use the dodge button to dodge attacks
        ///Press the shoot button to shoot enemies
        ///You can also use the shoot button to shoot enemies
        ///If you run out of health, you will lose the game
        ///If your health reaches zero, you lose
        ///Dont let the boss hit you
        ///Dont lose
        ///Dont get hit by enemies
        ///Your weapons do damage
        ///Use your weapons to defeat enemies
        ///Us [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string shiteTips {
            get {
                return ResourceManager.GetString("shiteTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totally tubular
        ///Better than UltraTelephone!
        ///ULTRAWHO?
        ///Minos Prime
        ///I&apos;m going to ultrakill you
        ///Welcome Noobs!
        ///Have fun.
        ///,&apos;:]
        ///FREE P RANK DOWNLOAD NOW!
        ///In the end it has to be this way.
        ///Made with love &lt;3
        ///CULT OF JAKITO SENDS ITS REGARDS!
        ///What&apos;s weave?
        ///ULTRAMOD MANAGER!
        ///Ultramodded ULTRAKILL
        ///ULTRAULTRAKILL
        ///play primordial hunger on the angry level loader
        ///Rated M for Machine
        ///HOW TO GET FREE P-RANK ULTRAKILL
        ///Hello Machine.
        ///Hello Machines.
        ///Hello Machines..
        ///Who are you?
        ///Good luck.
        ///It is a sa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string splashes {
            get {
                return ResourceManager.GetString("splashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] telephone2_assets_all {
            get {
                object obj = ResourceManager.GetObject("telephone2_assets_all", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] telephone2_scenes_all {
            get {
                object obj = ResourceManager.GetObject("telephone2_scenes_all", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ultratelephone2_monoscripts {
            get {
                object obj = ResourceManager.GetObject("ultratelephone2_monoscripts", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
