//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CultOfJakito.UltraTelephone2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CultOfJakito.UltraTelephone2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _20230331_153754 {
            get {
                object obj = ResourceManager.GetObject("_20230331_153754", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _20230420_163631 {
            get {
                object obj = ResourceManager.GetObject("_20230420_163631", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] absoluteterror {
            get {
                object obj = ResourceManager.GetObject("absoluteterror", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] aetsesye {
            get {
                object obj = ResourceManager.GetObject("aetsesye", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] afarft {
            get {
                object obj = ResourceManager.GetObject("afarft", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] artworks_dgGS7o4DGuYHt1xX_IjeBqw_t500x500 {
            get {
                object obj = ResourceManager.GetObject("artworks_dgGS7o4DGuYHt1xX_IjeBqw_t500x500", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] artworks_VZ1hrrVnmieDgPfw_09eQow_t500x500 {
            get {
                object obj = ResourceManager.GetObject("artworks_VZ1hrrVnmieDgPfw_09eQow_t500x500", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] awdjao {
            get {
                object obj = ResourceManager.GetObject("awdjao", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] aweaegasgere {
            get {
                object obj = ResourceManager.GetObject("aweaegasgere", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] awra35as4et5 {
            get {
                object obj = ResourceManager.GetObject("awra35as4et5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] badmove {
            get {
                object obj = ResourceManager.GetObject("badmove", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] baffled {
            get {
                object obj = ResourceManager.GetObject("baffled", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bear5 {
            get {
                object obj = ResourceManager.GetObject("bear5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bigassgloopy {
            get {
                object obj = ResourceManager.GetObject("bigassgloopy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Block_Creator_Glass {
            get {
                object obj = ResourceManager.GetObject("Block_Creator_Glass", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] boi {
            get {
                object obj = ResourceManager.GetObject("boi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bone {
            get {
                object obj = ResourceManager.GetObject("bone", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mega
        ///Based
        ///Cringe
        ///Super
        ///Gay
        ///Aromantic
        ///ULTRA
        ///Pro
        ///Hyper
        ///Peak
        ///Noob
        ///Final
        ///Ultimate
        ///Cowardly
        ///Elite
        ///Blue
        ///Red
        ///Stupid
        ///Stinky
        ///Smelly
        ///Lazy
        ///Awesome
        ///Magic
        ///Evil
        ///Kind
        ///The
        ///Skibidi
        ///Powerful
        ///Disgusting
        ///THE AMAZING
        ///Mid
        ///Masterful
        ///Goopy
        ///Funny
        ///Friendly
        ///Hostile
        ///LORD
        ///HOLY
        ///SAINT
        ///GOOBER
        ///PSYCHO
        ///BADASS
        ///GLISTENING
        ///BURNING
        ///Sir.
        ///Upside-Down
        ///Confused
        ///Listless
        ///Generous
        ///Blocky
        ///Round
        ///Enraged
        ///Angry
        ///Rude
        ///Rotund
        ///Caffeinated
        ///Combustable
        ///Menacing
        ///Fast
        ///Heroic
        ///Fair
        ///Epic
        ///Legendary
        ///Odd
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bossBar_prefixes {
            get {
                return ResourceManager.GetString("bossBar_prefixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE MAN
        ///(FINAL FORM)
        ///I
        ///II
        ///III
        ///IV
        ///V
        ///VI
        ///VII
        ///VIII
        ///IX
        ///X
        ///PHD
        ///M.D
        ///FROM OHIO
        ///WITH RIZZ
        ///JR.
        ///SR.
        ///ESQUIRE
        ///LORD OF CINDER
        ///LORD OF HELL
        ///OCCUPANT OF HELL
        ///BOSS
        ///PRIME
        ///THE FIFTH
        ///HELLS GUARDIAN
        ///SWAG MASTER
        ///The Everlasting
        ///The Desolate
        ///The Destroyer
        ///The Hungry
        ///:3
        ///The Squeamish
        ///The Tired
        ///The Broken
        ///The Cold
        ///The Abstracted
        ///B.A
        ///B.Sc
        ///M.A
        ///M.L.A. 
        ///M.F.A. 
        ///M.S.W. 
        ///M.L.
        ///B.Tech
        ///B.Ed
        ///Monarch
        ///DD
        ///OFM
        ///CSV
        ///The Incomplete
        ///The Rushed
        ///The Anointed
        ///The Revived
        ///Estranged.
        /// </summary>
        internal static string bossBar_suffixes {
            get {
                return ResourceManager.GetString("bossBar_suffixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bro {
            get {
                object obj = ResourceManager.GetObject("bro", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when
        ///you
        ///and
        ///the
        ///then
        ///when
        ///we
        ///was
        ///where
        ///and
        ///then
        ///he
        ///she
        ///they
        ///and
        ///it
        ///was
        ///awesome
        ///then
        ///you
        ///just
        ///about
        ///to
        ///too
        ///there
        ///their
        ///then
        ///they&apos;re
        ///not
        ///very
        ///huge
        ///big
        ///small
        ///sand-covered
        ///silly
        ///:3
        ///rot
        ///.
        /// </summary>
        internal static string cantReadWords {
            get {
                return ResourceManager.GetString("cantReadWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] catalog_wbp {
            get {
                object obj = ResourceManager.GetObject("catalog_wbp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] catalog_wbp1 {
            get {
                object obj = ResourceManager.GetObject("catalog_wbp1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CatExperiencee {
            get {
                object obj = ResourceManager.GetObject("CatExperiencee", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] chartreused {
            get {
                object obj = ResourceManager.GetObject("chartreused", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] chees1 {
            get {
                object obj = ResourceManager.GetObject("chees1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] coconut {
            get {
                object obj = ResourceManager.GetObject("coconut", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ComeHere {
            get {
                object obj = ResourceManager.GetObject("ComeHere", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cover2__4_ {
            get {
                object obj = ResourceManager.GetObject("cover2__4_", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] crydeath {
            get {
                object obj = ResourceManager.GetObject("crydeath", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DeathImage {
            get {
                object obj = ResourceManager.GetObject("DeathImage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dfgdth {
            get {
                object obj = ResourceManager.GetObject("dfgdth", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dog_stare_zoom {
            get {
                object obj = ResourceManager.GetObject("dog_stare_zoom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dogstare0 {
            get {
                object obj = ResourceManager.GetObject("dogstare0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dogstare1 {
            get {
                object obj = ResourceManager.GetObject("dogstare1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] drgd {
            get {
                object obj = ResourceManager.GetObject("drgd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] drghdtfhftgiu {
            get {
                object obj = ResourceManager.GetObject("drghdtfhftgiu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dug {
            get {
                object obj = ResourceManager.GetObject("dug", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dyftuftyuure {
            get {
                object obj = ResourceManager.GetObject("dyftuftyuure", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] earinfection {
            get {
                object obj = ResourceManager.GetObject("earinfection", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydraxous
        ///Waffle
        ///Zelzmiy
        ///Teamdoodz
        ///ZedDev
        ///Glitchy
        ///Agent Of Nyarlathotep
        ///JAKITO
        ///Hakita
        ///PITR
        ///Heckteck
        ///Action Dawg
        ///.
        /// </summary>
        internal static string enemyNames {
            get {
                return ResourceManager.GetString("enemyNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ermcat {
            get {
                object obj = ResourceManager.GetObject("ermcat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] F5GRMlEWUAAAiym {
            get {
                object obj = ResourceManager.GetObject("F5GRMlEWUAAAiym", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FbyFm47UcAEI1Cq {
            get {
                object obj = ResourceManager.GetObject("FbyFm47UcAEI1Cq", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FhOuLBjWIAwab1v {
            get {
                object obj = ResourceManager.GetObject("FhOuLBjWIAwab1v", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Fuel {
            get {
                object obj = ResourceManager.GetObject("Fuel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FwM5Y36XoAEO7r8 {
            get {
                object obj = ResourceManager.GetObject("FwM5Y36XoAEO7r8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Fx_3ZYsWcAIDlzG {
            get {
                object obj = ResourceManager.GetObject("Fx_3ZYsWcAIDlzG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] gobrae {
            get {
                object obj = ResourceManager.GetObject("gobrae", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] gorp {
            get {
                object obj = ResourceManager.GetObject("gorp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] hakitalightning {
            get {
                object obj = ResourceManager.GetObject("hakitalightning", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] herobrine {
            get {
                object obj = ResourceManager.GetObject("herobrine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] jnjhk {
            get {
                object obj = ResourceManager.GetObject("jnjhk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] kettamean {
            get {
                object obj = ResourceManager.GetObject("kettamean", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] maxresdefault__44_ {
            get {
                object obj = ResourceManager.GetObject("maxresdefault__44_", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] monkscream {
            get {
                object obj = ResourceManager.GetObject("monkscream", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ohdatsJudment {
            get {
                object obj = ResourceManager.GetObject("ohdatsJudment", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] padrick {
            get {
                object obj = ResourceManager.GetObject("padrick", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] plink {
            get {
                object obj = ResourceManager.GetObject("plink", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your legs get cut off, would it hurt?
        ///101110010000101101011101101010110
        ///Weeeeeeeeeeeeeeeee
        ///How the fuck did a 1000-THR get in hell
        ///I thought a cerberus was a type of dog...
        ///What exactly generates the power from blood?
        ///Do guttermen dream?
        ///If Sisyphus could just break out of the prison, why did he wait?
        ///I just [EXCEPTION][EXCEPTION][EXCEPTION] Mindflayer [EXCEPTION]
        ///What if Guttertanks were always meant to topple?
        ///What if he made it up?
        ///What the heck them blue orbs
        ///What does P even stand for? P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ponder {
            get {
                return ResourceManager.GetString("ponder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pronounssoy {
            get {
                object obj = ResourceManager.GetObject("pronounssoy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] r {
            get {
                object obj = ResourceManager.GetObject("r", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] roachcarving {
            get {
                object obj = ResourceManager.GetObject("roachcarving", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] scientistshavediscovered {
            get {
                object obj = ResourceManager.GetObject("scientistshavediscovered", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sergsrhds {
            get {
                object obj = ResourceManager.GetObject("sergsrhds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] shader_unitybuiltinshaders {
            get {
                object obj = ResourceManager.GetObject("shader_unitybuiltinshaders", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you know you can shoot enemies to hurt them
        ///Hit the boss until its health bar is empty to win
        ///You can also dodge attacks by moving out of the way
        ///You can also use the dodge button to dodge attacks
        ///Press the shoot button to shoot enemies
        ///You can also use the shoot button to shoot enemies
        ///If you run out of health, you will lose the game
        ///If your health reaches zero, you lose
        ///Dont let the boss hit you
        ///Dont lose
        ///Dont get hit by enemies
        ///Your weapons do damage
        ///Use your weapons to defeat enemies
        ///Us [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string shiteTips {
            get {
                return ResourceManager.GetString("shiteTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] skol {
            get {
                object obj = ResourceManager.GetObject("skol", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SmartSelect_20211116_174331 {
            get {
                object obj = ResourceManager.GetObject("SmartSelect_20211116_174331", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SmartSelect_20211125_164814 {
            get {
                object obj = ResourceManager.GetObject("SmartSelect_20211125_164814", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SmartSelect_s20210321_152814 {
            get {
                object obj = ResourceManager.GetObject("SmartSelect_s20210321_152814", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] soypoint {
            get {
                object obj = ResourceManager.GetObject("soypoint", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totally tubular
        ///Better than UltraTelephone!
        ///ULTRAWHO?
        ///Minos Prime
        ///I&apos;m going to ultrakill you
        ///Welcome Noobs!
        ///Have fun.
        ///,&apos;:]
        ///FREE P RANK DOWNLOAD NOW!
        ///In the end it has to be this way.
        ///Made with love &lt;3
        ///CULT OF JAKITO SENDS ITS REGARDS!
        ///What&apos;s weave?
        ///ULTRAMOD MANAGER!
        ///Ultramodded ULTRAKILL
        ///ULTRAULTRAKILL
        ///play primordial hunger on the angry level loader
        ///Rated M for Machine
        ///HOW TO GET FREE P-RANK ULTRAKILL
        ///Hello Machine.
        ///Hello Machines.
        ///Hello Machines..
        ///Who are you?
        ///Good luck.
        ///It is a sa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string splashes {
            get {
                return ResourceManager.GetString("splashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] spongecry {
            get {
                object obj = ResourceManager.GetObject("spongecry", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] stare {
            get {
                object obj = ResourceManager.GetObject("stare", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] steamhappy {
            get {
                object obj = ResourceManager.GetObject("steamhappy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] steamhappy1 {
            get {
                object obj = ResourceManager.GetObject("steamhappy1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Stinker {
            get {
                object obj = ResourceManager.GetObject("Stinker", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] t56f7yit657yf7t6fyiuk {
            get {
                object obj = ResourceManager.GetObject("t56f7yit657yf7t6fyiuk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tarwaee {
            get {
                object obj = ResourceManager.GetObject("tarwaee", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] telephone2_assets_all {
            get {
                object obj = ResourceManager.GetObject("telephone2_assets_all", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] telephone2_scenes_all {
            get {
                object obj = ResourceManager.GetObject("telephone2_scenes_all", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] twodabloons {
            get {
                object obj = ResourceManager.GetObject("twodabloons", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ultratelephone2_monoscripts {
            get {
                object obj = ResourceManager.GetObject("ultratelephone2_monoscripts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] unnamed__4_ {
            get {
                object obj = ResourceManager.GetObject("unnamed__4_", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vgvhure {
            get {
                object obj = ResourceManager.GetObject("vgvhure", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///aa
        ///aaa
        ///aaron
        ///ab
        ///abandoned
        ///abc
        ///aberdeen
        ///abilities
        ///ability
        ///able
        ///aboriginal
        ///abortion
        ///about
        ///above
        ///abraham
        ///abroad
        ///abs
        ///absence
        ///absent
        ///absolute
        ///absolutely
        ///absorption
        ///abstract
        ///abstracts
        ///abu
        ///abuse
        ///ac
        ///academic
        ///academics
        ///academy
        ///acc
        ///accent
        ///accept
        ///acceptable
        ///acceptance
        ///accepted
        ///accepting
        ///accepts
        ///access
        ///accessed
        ///accessibility
        ///accessible
        ///accessing
        ///accessories
        ///accessory
        ///accident
        ///accidents
        ///accommodate
        ///accommodation
        ///accommodations
        ///accompanied
        ///accompanying
        ///accomplish
        ///ac [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wordlist_10000 {
            get {
                return ResourceManager.GetString("wordlist.10000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] yeahlmao {
            get {
                object obj = ResourceManager.GetObject("yeahlmao", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
